name: mash
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  go_router: ^13.2.4
  flutter_bloc: ^8.1.5
  dio: ^5.4.2+1
  get_storage: ^2.1.1
  hive: ^2.2.3
  firebase_messaging: ^14.8.1
  flutter_local_notifications: ^17.0.0
  path_provider: ^2.1.3
  freezed_annotation: ^2.4.1
  internet_connection_checker: ^1.0.0+1
  flutter_svg:
  google_fonts:
  line_icons:
  otp_text_field:
  cloud_firestore:
  cached_network_image:
  fl_chart:
  intl: ^0.19.0
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  dev: ^1.0.0
  mockito: ^5.4.4
  equatable: ^2.0.5
  injectable: ^2.4.1
  injectable_generator: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/mash/presentation/pages/
    - lib/mash/presentation/pages/auth/
    - lib/mash/presentation/pages/home/
    - lib/mash/presentation/pages/home/addOn/
    - lib/mash/presentation/pages/home/library/
    - lib/mash/presentation/pages/home/widgets/
    - lib/mash/presentation/pages/home/homeWork/
    - lib/mash/presentation/pages/home/timeTable/
    - lib/mash/presentation/pages/profile/
    - lib/mash/presentation/pages/bottomBar/
    - lib/mash/presentation/pages/dashboard/
    - lib/mash/presentation/pages/dashboard/widgets/
