name: mash
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: null
#  cloud_firestore: null
  # cloud_firestore: ^4.17.2
  confetti: null
  cupertino_icons: ^1.0.6
  dev: ^1.0.0
  dio: ^5.4.2+1
  equatable: ^2.0.5
  shimmer: ^3.0.0
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  flutter_local_notifications: ^17.0.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_storage: ^2.1.1
  go_router: ^13.2.4
  google_fonts: null
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.4.1
  injectable_generator: ^2.6.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  line_icons: null
  otp_text_field: null
  path_provider: ^2.1.3
  device_info_plus: ^10.1.0
  firebase_auth: ^4.19.5
  uuid: ^4.4.0
  lottie: ^3.1.0
  cloud_firestore: ^4.17.3
  firebase_messaging: ^14.9.2
  firebase_core: ^2.31.0
  google_maps_flutter: ^2.2.8
  location: ^6.0.2
  flutter_polyline_points: ^2.0.0
  flutter_emoji_feedback: ^0.3.0
  flutter_pdfview: ^1.3.2
dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter 
  hive_generator: ^2.0.1
  image_picker:
  photo_view:
  lottie:
  url_launcher:
  

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: SofiaPro
      fonts:
        - asset: fonts/sofi_pro_regular.otf
          weight: 900
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
