name: mash
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: null
  cloud_firestore: null
  confetti: null
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dev: ^1.0.0
  dio: ^5.4.2+1
  equatable: ^2.0.5
  firebase_messaging: ^14.8.1
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^17.0.0
  flutter_svg: null
  freezed_annotation: ^2.4.1
  get_storage: ^2.1.1
  go_router: ^13.2.4
  google_fonts: null
  hive: ^2.2.3
  injectable: ^2.4.1
  injectable_generator: ^2.6.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  line_icons: null
  mockito: ^5.4.4
  otp_text_field: null
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.9

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SofiaPro
      fonts:
        - asset: fonts/sofi_pro_regular.otf
          weight: 900
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
